<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>skye_back.Presentation</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
        <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="9.0.6" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.6" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\skye-back.Application\skye-back.Application.csproj" />
      <ProjectReference Include="..\skye-back.Contracts\skye-back.Contracts.csproj" />
      <ProjectReference Include="..\skye-back.Domain\skye-back.Domain.csproj" />
      <ProjectReference Include="..\skye-back.Infrastructure\skye-back.Infrastructure.csproj" />
    </ItemGroup>

</Project>
