// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using skye_back.Infrastructure;

#nullable disable

namespace skye_back.Infrastructure.Migrations
{
    [DbContext(typeof(SkyeBackDbContext))]
    partial class SkyeBackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("skye_back.Domain.Conversation.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("skye_back.Domain.Message.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversion_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("skye_back.Domain.ModelInfo.ModelInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ContextWindow")
                        .HasColumnType("integer")
                        .HasColumnName("context_window");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_model_info");

                    b.ToTable("model_info", (string)null);
                });

            modelBuilder.Entity("skye_back.Domain.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("skye_back.Domain.UserConversations.UserConversation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.HasKey("UserId", "ConversationId")
                        .HasName("pk_user_conversations");

                    b.HasIndex("ConversationId");

                    b.ToTable("user_conversations", (string)null);
                });

            modelBuilder.Entity("skye_back.Domain.UserPreference.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("StreamByDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("stream_by_default");

                    b.Property<string>("StreamPromptDefault")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stream_prompt_default");

                    b.HasKey("UserId")
                        .HasName("pk_user_preference");

                    b.ToTable("user_preference", (string)null);
                });

            modelBuilder.Entity("skye_back.Domain.Conversation.Conversation", b =>
                {
                    b.OwnsOne("skye_back.Domain.Conversation.Model", "Model", b1 =>
                        {
                            b1.Property<Guid>("ConversationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("model");

                            b1.HasKey("ConversationId");

                            b1.ToTable("conversations");

                            b1.WithOwner()
                                .HasForeignKey("ConversationId");
                        });

                    b.OwnsOne("skye_back.Domain.Conversation.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("ConversationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("title");

                            b1.HasKey("ConversationId");

                            b1.ToTable("conversations");

                            b1.WithOwner()
                                .HasForeignKey("ConversationId");
                        });

                    b.Navigation("Model")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("skye_back.Domain.Message.Message", b =>
                {
                    b.HasOne("skye_back.Domain.Conversation.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("skye_back.Domain.Message.Content", "Content", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20000)
                                .HasColumnType("character varying(20000)")
                                .HasColumnName("content");

                            b1.HasKey("MessageId");

                            b1.ToTable("messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.OwnsOne("skye_back.Domain.Message.Model", "Model", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("model");

                            b1.HasKey("MessageId");

                            b1.ToTable("messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.OwnsOne("skye_back.Domain.Message.Role", "Role", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("role");

                            b1.HasKey("MessageId");

                            b1.ToTable("messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Model")
                        .IsRequired();

                    b.Navigation("Role")
                        .IsRequired();
                });

            modelBuilder.Entity("skye_back.Domain.ModelInfo.ModelInfo", b =>
                {
                    b.OwnsOne("skye_back.Domain.ModelInfo.Model", "Model", b1 =>
                        {
                            b1.Property<Guid>("ModelInfoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("model");

                            b1.HasKey("ModelInfoId");

                            b1.HasIndex("Value");

                            b1.ToTable("model_info");

                            b1.WithOwner()
                                .HasForeignKey("ModelInfoId");
                        });

                    b.OwnsOne("skye_back.Domain.ModelInfo.PricePerThousand", "PriceInputPer1K", b1 =>
                        {
                            b1.Property<Guid>("ModelInfoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("price_input_value");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_input_currency");

                            b1.HasKey("ModelInfoId");

                            b1.ToTable("model_info");

                            b1.WithOwner()
                                .HasForeignKey("ModelInfoId");
                        });

                    b.OwnsOne("skye_back.Domain.ModelInfo.PricePerThousand", "PriceOutputPer1K", b1 =>
                        {
                            b1.Property<Guid>("ModelInfoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("price_output_value");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("price_output_currency");

                            b1.HasKey("ModelInfoId");

                            b1.ToTable("model_info");

                            b1.WithOwner()
                                .HasForeignKey("ModelInfoId");
                        });

                    b.Navigation("Model")
                        .IsRequired();

                    b.Navigation("PriceInputPer1K");

                    b.Navigation("PriceOutputPer1K");
                });

            modelBuilder.Entity("skye_back.Domain.User.User", b =>
                {
                    b.OwnsOne("skye_back.Domain.User.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("skye_back.Domain.User.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("skye_back.Domain.User.YandexId", "YandexId", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("yandex_id");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("YandexId")
                        .IsRequired();
                });

            modelBuilder.Entity("skye_back.Domain.UserConversations.UserConversation", b =>
                {
                    b.HasOne("skye_back.Domain.Conversation.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("skye_back.Domain.User.User", null)
                        .WithMany("UserConversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("skye_back.Domain.UserPreference.UserPreference", b =>
                {
                    b.OwnsOne("skye_back.Domain.UserPreference.Model", "DefaultModel", b1 =>
                        {
                            b1.Property<Guid>("UserPreferenceUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("default_model");

                            b1.HasKey("UserPreferenceUserId");

                            b1.ToTable("user_preference");

                            b1.WithOwner()
                                .HasForeignKey("UserPreferenceUserId");
                        });

                    b.OwnsOne("skye_back.Domain.UserPreference.Theme", "Theme", b1 =>
                        {
                            b1.Property<Guid>("UserPreferenceUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("theme");

                            b1.HasKey("UserPreferenceUserId");

                            b1.ToTable("user_preference");

                            b1.WithOwner()
                                .HasForeignKey("UserPreferenceUserId");
                        });

                    b.Navigation("DefaultModel")
                        .IsRequired();

                    b.Navigation("Theme")
                        .IsRequired();
                });

            modelBuilder.Entity("skye_back.Domain.User.User", b =>
                {
                    b.Navigation("UserConversations");
                });
#pragma warning restore 612, 618
        }
    }
}
